<?php
return array(
	'BE' => array(
		'disable_exec_function' => 0,
		'explicitADmode' => 'explicitAllow',
		'fileCreateMask' => '0666',
		'folderCreateMask' => '2777',
		'installToolPassword' => '5f4dcc3b5aa765d61d8327deb882cf99',
		'loginSecurityLevel' => 'rsa',
	),
	'DB' => array(
		'database' => 'dummyfab',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => '127.0.0.1',
		'password' => 'root',
		'username' => 'root',
	),
	'EXT' => array(
		'extConf' => array(
			'automaketemplate' => 'a:0:{}',
			'fluidcontent' => 'a:0:{}',
			'fluidcontent_bootstrap' => 'a:0:{}',
			'fluidpages' => 'a:0:{}',
			'fluidpages_bootstrap' => 'a:0:{}',
			'fluidwidget' => 'a:0:{}',
			'flux' => 'a:2:{s:9:"debugMode";s:1:"0";s:7:"compact";s:1:"0";}',
			'indexed_search' => 'a:18:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:21:"enableMetaphoneSearch";s:1:"1";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"0";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";}',
			'jquerycolorbox' => 'a:0:{}',
			'linkvalidator' => 'a:0:{}',
			'news' => 'a:10:{s:29:"removeListActionFromFlexforms";s:1:"2";s:20:"pageModuleFieldsNews";s:313:"LLL:EXT:news/Resources/Private/Language/locallang_be.xml:pagemodule_simple=title,datetime;LLL:EXT:news/Resources/Private/Language/locallang_be.xml:pagemodule_advanced=title,datetime,teaser,category;LLL:EXT:news/Resources/Private/Language/locallang_be.xml:pagemodule_complex=title,datetime,teaser,category,archive;";s:24:"pageModuleFieldsCategory";s:17:"title,description";s:6:"tagPid";s:1:"1";s:13:"prependAtCopy";s:1:"1";s:19:"categoryRestriction";s:0:"";s:22:"contentElementRelation";s:1:"0";s:13:"manualSorting";s:1:"0";s:11:"archiveDate";s:4:"date";s:12:"showImporter";s:1:"0";}',
			'realurl' => 'a:5:{s:10:"configFile";s:54:"typo3conf/ext/speciality/Configuration/Php/RealUrl.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'rtehtmlarea' => 'a:13:{s:21:"noSpellCheckLanguages";s:23:"ja,km,ko,lo,th,zh,b5,gb";s:15:"AspellDirectory";s:15:"/usr/bin/aspell";s:17:"defaultDictionary";s:2:"en";s:14:"dictionaryList";s:2:"en";s:20:"defaultConfiguration";s:105:"Typical (Most commonly used features are enabled. Select this option if you are unsure which one to use.)";s:12:"enableImages";s:1:"1";s:20:"enableInlineElements";s:1:"0";s:19:"allowStyleAttribute";s:1:"1";s:24:"enableAccessibilityIcons";s:1:"0";s:16:"enableDAMBrowser";s:1:"0";s:16:"forceCommandMode";s:1:"0";s:15:"enableDebugMode";s:1:"0";s:23:"enableCompressedScripts";s:1:"1";}',
			'saltedpasswords' => 'a:2:{s:3:"FE.";a:2:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";}s:3:"BE.";a:2:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";}}',
			'scheduler' => 'a:4:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";}',
			'speciality' => 'a:0:{}',
			'uncache' => 'a:0:{}',
			'vhs' => 'a:0:{}',
			'workspaces' => 'a:0:{}',
			'wt_spamshield' => 'a:10:{s:12:"useNameCheck";s:1:"1";s:12:"usehttpCheck";s:1:"3";s:9:"notUnique";s:0:"";s:13:"honeypodCheck";s:1:"1";s:15:"useSessionCheck";s:1:"1";s:16:"SessionStartTime";s:2:"10";s:14:"SessionEndTime";s:3:"600";s:10:"AkismetKey";s:0:"";s:12:"email_notify";s:0:"";s:3:"pid";s:1:"0";}',
		),
		'extListArray' => array(
			0 => 'info',
			1 => 'perm',
			2 => 'func',
			3 => 'filelist',
			4 => 'about',
			5 => 'version',
			6 => 'tsconfig_help',
			7 => 'context_help',
			8 => 'extra_page_cm_options',
			9 => 'impexp',
			10 => 'sys_note',
			11 => 'tstemplate',
			12 => 'tstemplate_ceditor',
			13 => 'tstemplate_info',
			14 => 'tstemplate_objbrowser',
			15 => 'tstemplate_analyzer',
			16 => 'func_wizards',
			17 => 'wizard_crpages',
			18 => 'wizard_sortpages',
			19 => 'lowlevel',
			20 => 'install',
			21 => 'belog',
			22 => 'beuser',
			23 => 'aboutmodules',
			24 => 'setup',
			25 => 'taskcenter',
			26 => 'info_pagetsconfig',
			27 => 'viewpage',
			28 => 'rtehtmlarea',
			29 => 'css_styled_content',
			30 => 't3skin',
			31 => 't3editor',
			32 => 'reports',
			33 => 'felogin',
			34 => 'form',
			35 => 'introduction',
			36 => 'rsaauth',
			37 => 'saltedpasswords',
			38 => 'workspaces',
			39 => 'scheduler',
			40 => 'linkvalidator',
			42 => 'realurl',
			43 => 'news',
			44 => 'indexed_search',
			45 => 'wt_spamshield',
			46 => 'jquerycolorbox',
			47 => 'flux',
			48 => 'vhs',
			49 => 'fluidwidget',
			50 => 'fluidpages',
			52 => 'fluidcontent',
			53 => 'fluidcontent_bootstrap',
			54 => 'uncache',
			55 => 'speciality',
		),
	),
	'FE' => array(
		'loginSecurityLevel' => 'rsa',
		'pageNotFound_handling' => 'http://dummy.fab/index.php?id=16',
	),
	'GFX' => array(
		'gdlib_png' => 1,
		'im_path' => '/usr/local/bin/',
		'im_path_lzw' => '',
		'im_version_5' => 'gm',
		'jpg_quality' => '80',
	),
	'SYS' => array(
		'compat_version' => '6.0',
		'encryptionKey' => '2b044d8946e3c90f505ff6fff2b161170535e8d356481432e3032f4084f1c6f6ed57b90f3fdad20203b859f79f9a1728',
		'sitename' => 'New TYPO3 site',
	),
);
?>